### ISSUE TITLE
Añadir excepcion para la imagenes 

### ISSUE THREAD

**Issue by HALCONDEORO** [benjavalero/replacer#100]
Buenas, debido a una reversion que un usuario hizo a una correcion que hice a unos dias me he dado cuenta que la herramienta da opcion a corregir palabras en nombres de imagen, aqui el ejemplo practico:
https://es.wikipedia.org/w/index.php?title=Gij%C3%B3n&oldid=prev&diff=119651094&diffmode=source
Le di el agradecimiento porque me ha ayudado a darme cuenta que es necesario añadir una excepcion para los .jpg y .png

**Comment by benjavalero** [comment]
Efectivamente, la herramienta ignora los nombres de archivos, pero se le está escapando este caso:
```
 | foto5a = Universidad Laboral de Gijon (2).jpg{{!}}Laboral Universidad de la Cultural (ex Universidad Laboral de Gijón)
```

**Comment by benjavalero** [comment]
No se está teniendo en cuenta el caso en que el nombre del archivo esté seguido de `{`, que se usa para separar el archivo y su descripción en algunas plantillas.
