### ISSUE TITLE
Idea añadir elecciones en subtipo

### ISSUE THREAD

**Issue by HALCONDEORO** [benjavalero/replacer#106]
Buenas creo que en la seccion Lista de reemplazos se podria añadir una opcion para añadir un editor de opciones que direcciona a la wiki.
Por ejemplo en el posible fallo de "contaria" te da la opcion de cambiarlo por contraria, pero podria ser contaría como conjunción del verbo contar.
Estaria bien una dirección directa en el listado de reemplazos a https://es.wikipedia.org/wiki/Wikipedia:Corrector_ortogr%C3%A1fico/Listado con su letra si es posible.
¿Que piensas?

**Comment by benjavalero** [comment]
Doy esta tarea por cerrada. Considero que la herramienta actualmente da opciones suficientes:
- Permite editar el fragmento de texto que rodea al reemplazo, y en particular permite editar el reemplazo en sí en caso de que las alternativas ofrecidas no sean suficientes.
- Hay un enlace a la Ayuda que contiene la explicación de cada tipo con enlaces a los listados
