### ISSUE TITLE
Esta dando error 

### ISSUE THREAD

**Issue by HALCONDEORO** [benjavalero/replacer#107]
Error al buscar artículos con reemplazos: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection

**Comment by benjavalero** [comment]
Pasó hace un mes o así lo mismo y se solucionó “solo” (sin tilde, jeje). No hay nada que pueda hacer la herramienta, es la base de datos de las herramientas de Wikipedia que da problemas de disponibilidad. 

Por desgracia me temo que si vuelve a pasar lo único que podemos hacer es esperar.

**Comment by benjavalero** [comment]
La causa de error de esta incidencia está obsoleta. Replacer ahora usa otro sistema para interactuar con su base de datos.

Y en caso de que la base de datos deje temporalmente de estar disponible, por causas ajenas a la herramienta, ya que está alojada en servidores de Wikipedia, entonces no hay nada que se pueda hacer salvo esperar a que la misma vuelva a estar disponible.
