### ISSUE TITLE
reemplazo personalizado tarda muchísimo

### ISSUE THREAD

**Issue by jserquera** [benjavalero/replacer#126]
Hola... gran herramienta...

Hace un tiempo que el reemplazo personalizado tarda muchísimo en "buscar artículo aleatorio de tipo Personalizado...

antes funcionaba muy rápido

**Comment by benjavalero** [comment]
Hola, ¿puedes dar un ejemplo más concreto de reemplazo que vaya tan lento?

**Comment by jserquera** [comment]
Hoy he probado cambiar "el fue" por "él fue"

**Comment by jserquera** [comment]
He encontrado un patrón.... debe haber algo acumulativo... la primera vez que pones un reemplazo personalizado va muy rápido.... las siguientes veces, en días distintos, con el mismo reemplazo, ya va cada vez más lento

**Comment by benjavalero** [comment]
Muchas gracias por el apunte. Lo tengo que analizar con tranquilidad, pero es cierto que esta funcionalidad va muy lenta cuando es un reemplazo con muchas ocurrencias, ya que son muchas las páginas de Wikipedia que hay que recuperar y comprobar. En este caso no hay un pre-procesado como en los términos de los listados.

**Comment by benjavalero** [comment]
Efectivamente he comprobado que los personalizados pueden ir lentísimos cuando no se distinguen mayúsculas. Por ejemplo si busco «podriamos», como internamente no se usa la propiedad `insource` de Wikipedia, esta encuentra más de 2000 resultados que son prácticamente todos falsos positivos.

Esto implica que que Replacer recupere esas 2000 páginas de Wikipedia para al final solo usar unas pocas.

Como primera opción de optimización, quizá se podría modificar para que cargue los contenidos de las páginas en lotes. En principio en los no personalizados no haría falta porque asumimos que la mayoría de los casos que encontramos son buenos.
