### ISSUE TITLE
Connection pooling is against Toolforge rules

### ISSUE THREAD

**Issue by supertassu** [benjavalero/replacer#142]
The replacer tool currently maintains ten idle connections to the ToolsDB database. Using connection pooling to maintain idle database connections is against Toolforge policy: https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#Connection_handling_policy. Please update the tool to only open connections when needed. Thanks in advance!

**Comment by benjavalero** [comment]
I am afraid this may have been caused by the last toolforge outages in the recent days.

Anyway I will investigate in order to update the tool so it behaves as you describe.

Thanks for the warning.

**Comment by benjavalero** [comment]
@supertassu 

These are the default configuration for connection pooling in Replacer application.

Do you recommend me to tweak them?

On the other hand, I will try to improve some heavy query I have detected.

![imagen](https://user-images.githubusercontent.com/1579843/230584347-3a41b8dc-76fc-4ed8-8a94-634fdfa414a6.png)

**Comment by benjavalero** [comment]
I have just restarted the tool setting the property `maximum-pool-size` to `2`. Let's see how it behaves.

**Comment by benjavalero** [comment]
After several weeks, I found issues every now and then. At July 2023 (one year ago) I set the property (see my previous comment) to `3` and it has worked nice so far, so I will let this value of `3` if you have no problems with it and close the ticket.
