### ISSUE TITLE
Buscar excepciones para los errores más comunes

### ISSUE THREAD

**Issue by benjavalero** [benjavalero/replacer#45]
1. Ortografía | sólo | 149934
2. Ortografía | records | 89022
3. Ortografía | aún | 80603
4. Ortografía | nº | 67713
5. Ortografía | éste | 57939
6. Ortografía | maria | 47674
7. Ortografía | sky | 39728
8. Ortografía | simon | 36127
9. Ortografía | Alex | 35665
10. Ortografía | Domingo | 35236
11. Ortografía | ésta | 33821
12. Ortografía | junior | 29480
13. Ortografía | Paris | 26560
14. Ortografía | round | 24795
15. Ortografía | Mayo | 23628
16. Ortografía | Julio | 23109
17. Ortografía | angeles | 22440
18. Ortografía | Victor | 22123
19. Ortografía | rio | 21598
20. Ortografía | america | 21136

**Comment by HALCONDEORO** [comment]
Para añadir excepciones se podria añadir en domingo que no salga si va precedido por Santo, osea Santo Domingo

**Comment by HALCONDEORO** [comment]
Para Manchester si va seguido por United no deberia aparecer, ya que el club no lleva tilde.

**Comment by HALCONDEORO** [comment]
Este y solo no deberian aparecer, ya que segun la RAE se escriben sin tilde.
https://www.rae.es/consultas/el-adverbio-solo-y-los-pronombres-demostrativos-sin-tilde

**Comment by HALCONDEORO** [comment]
Ahora mismo Eibar tiene mas de 3000 se pueden bajar si se quitan todos los que van precedidos por SD, por el equipo de futbol, quitar si es SD Eibar.

**Comment by benjavalero** [comment]
- Añado excepciones para los errores más comunes. Incluyo la referente al SD Eibar aunque no sea una de las más comunes.
- Elimino la excepción para "sólo" y "éste" (y derivados). Aunque la RAE es clara en cuanto al uso recomendado, hay mucha discrepancia entre los usuarios. Por eso prefiero dejar los términos para corregir, aunque son de los que más casos tienen.
