### ISSUE TITLE
Añadir información de contacto

### ISSUE THREAD

**Issue by benjavalero** [benjavalero/replacer#70]
Añadir más información en mi usuario de la Wikipedia y en la herramienta para que se sepa que soy el autor y que contacten conmigo.

**Comment by HALCONDEORO** [comment]
Esto es bastante importante, a mi me ha costado llegar hasta aqui.

**Comment by HALCONDEORO** [comment]
¿Crees que en el resumen de edicion se podria poner un enlace a la herramienta?
Ahora es asi: http://prntscr.com/pas7jy
Lo mismo pero que al hacer click te lleve a la pagina principal de la herramienta, ya que tenemos muy pocos usuarios y que pasen de  1000 ediciones creo que 5.

**Comment by benjavalero** [comment]
> ya que tenemos muy pocos usuarios y que pasen de 1000 ediciones creo que 5.

Hola @HALCONDEORO ¿cómo has obtenido este dato?

**Comment by benjavalero** [comment]
En cuanto a incluir un enlace a la herramienta, según la documentación actual no es posible incluir enlaces externos en el resumen de la edición, pero sí enlaces internos:

https://en.wikipedia.org/wiki/Help:Edit_summary#Edit_summary_properties_and_features

Por lo tanto, lo mejor es apuntar a un página de la Wikipedia (bajo mi usuario) donde aparezca el enlace externo a la herramienta, así como los detalles sobre cómo funciona la misma.

**Comment by benjavalero** [comment]
La próxima versión incluirá un símbolo de la Wikipedia que enlazará con la página creada para la herramienta:

https://es.wikipedia.org/wiki/Usuario:Benjavalero/Replacer

**Comment by HALCONDEORO** [comment]
> 
> 
> > ya que tenemos muy pocos usuarios y que pasen de 1000 ediciones creo que 5.
> 
> Hola @HALCONDEORO ¿cómo has obtenido este dato?

https://tools.wmflabs.org/replacer/stats

Aunque pone admin todos tenemos acceso, y a la indexación lo mismo.
