### ISSUE TITLE
Mostrar artículos con más errores

### ISSUE THREAD

**Issue by benjavalero** [benjavalero/replacer#72]
Quizá se podría añadir la opción de añadir la plantilla `copyedit` e incluso ignorar los artículos con esta plantilla.

**Comment by HALCONDEORO** [comment]
Buenas soy MarcoTevar en la wikipedia y uso muy a menudo esta herramienta suelo, voy a ve rsi puedo ayudarte con ideas y reportar algun bug encontrado, sobre este issue creo que todos los articulos que tengan alguna plantilla roja y puede que alguna de las amarilla sno deberian aparecer, ya que seran destruidas y no vale la pena editarlas.

**Comment by benjavalero** [comment]
Hola Marco, muchas gracias por tu comentario.

Por favor, ¿podrías ponerme algún ejemplo de "plantilla roja" y "plantilla amarilla"? ¿Te refieres a plantillas como "Copyedit"?

Sinceramente ahora mismo no tengo muy claro a qué te refieres.

**Comment by HALCONDEORO** [comment]
Las rojas serian las que estan relacionadas con la destruccion de un articulo:

https://es.wikipedia.org/wiki/Plantilla:Destruir o https://es.wikipedia.org/wiki/Wikipedia:Pol%C3%ADtica_de_borrado

Algunas amarillas serian las de wikificar o desactualizado ya que al necesitar un gran cambio muchas palabras serian cambiadas y seria un trabajo "sin sentido" pero cuando la mayoria de las correcciones estuviesen solucionadas se podrian añadir, con un tipico si hay menos de 10k posibles ediciones se podria abrir las amarillas.
Es solo una opinion, ¿que piensas?

**Comment by benjavalero** [comment]
La próxima versión ignorará los artículos conteniendo las plantillas "Destruir" y "CopyEdit".

**Comment by benjavalero** [comment]
Se han añadido más casos de plantillas. Si la página en cuestión contiene alguna de ellas, esta será ignorada.

**Comment by benjavalero** [comment]
Lista de plantillas para las que, si aparecen en alguna parte del texto de una página, Replacer ignora dicha página completamente:

https://github.com/benjavalero/replacer/blob/master/replacer-backend/src/main/resources/ignorable-templates.xml

**Comment by benjavalero** [comment]
Se ha añadido una funcionalidad (solo para administrador de momento, no disponible para el resto de usuarios) para listar las páginas con más reemplazos por revisar.
