### ISSUE TITLE
Compuestos-->la primer

### ISSUE THREAD

**Issue by HALCONDEORO** [benjavalero/replacer#99]
Buenas, en ese compuesto en las opciones para cambiarlo solo esta la primer**a**,  en algunas ocasiones el fallo esta en que es masculino y pone la, en vez de el primer o lo primero, segun el caso, me ha pasado en algunos casos y he tenido que cerrar la pestaña.

**Comment by benjavalero** [comment]
Hola @HALCONDEORO, muchas gracias por tu comentario.

He añadido como opciones:
- el primer
- lo primero
Las nuevas sugerencias deberían aparecer en una hora aproximadamente.

Por cierto, los errores "compuestos" son algo "de mi cosecha". Puedes encontrar la lista en https://es.wikipedia.org/wiki/Usuario:Benjavalero/ComposedMisspellings.

Por otra parte, si hay un error que no puedes reemplazar fácilmente con la herramienta, siempre puedes abrir el artículo en la Wikipedia y editarlo manualmente, o bien pulsar el botón "Guardar sin cambios" que marca el artículo como revisado, aunque no haya sido resuelto realmente. Esto último no es lo ideal, pero te permite seguir revisando otros artículos.
